/** Shared layout & typography tokens aligned with User Management Figma specs */

export const getUserManagementStyles = (c) => ({
  dataCard: {
    bgcolor: c.pureWhite,
    border: `1px solid ${c.silverGray}`,
    borderRadius: '16px',
    overflow: 'hidden',
  },
  toolbarRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 2,
    px: 3,
    pt: 3,
    pb: 2,
  },
  tableWrap: {
    pt: 3,
    mt: 0.5,
    borderTop: `1px solid ${c.silverGray}`,
  },
  searchField: {
    width: { xs: '100%', sm: 280 },
    flexShrink: 0,
    '& .MuiOutlinedInput-root': {
      height: 40,
      borderRadius: '8px',
      bgcolor: c.pureWhite,
      fontSize: 14,
      letterSpacing: '-0.14px',
      '& fieldset': { borderColor: c.lightGrayCCC },
      '&:hover fieldset': { borderColor: c.lightGrayCCC },
      '&.Mui-focused fieldset': { borderColor: c.ashGray, borderWidth: 1 },
    },
    '& .MuiOutlinedInput-input': {
      py: '10px',
      px: 0,
      '&::placeholder': { color: c.stoneGray, opacity: 1 },
    },
  },
  filterSelect: {
    height: 40,
    minWidth: 72,
    borderRadius: '8px',
    bgcolor: c.pureWhite,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: '-0.14px',
    color: c.pureBlack,
    '& .MuiOutlinedInput-notchedOutline': { borderColor: c.lightGrayCCC },
    '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: c.lightGrayCCC },
    '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: c.ashGray,
      borderWidth: 1,
    },
  },
  primaryButton: {
    height: 40,
    px: 2,
    bgcolor: c.goldenSun,
    color: c.pureBlack,
    fontWeight: 600,
    fontSize: 14,
    textTransform: 'none',
    borderRadius: '8px',
    boxShadow: 'none',
    '&:hover': { bgcolor: c.goldenSunHover, boxShadow: 'none' },
  },
  tableHeaderCell: {
    py: '12px',
    px: '24px',
    pb: '8px',
    height: 48,
    fontSize: 12,
    fontWeight: 700,
    lineHeight: '16px',
    color: c.ashGray,
    textTransform: 'uppercase',
    bgcolor: c.pureWhite,
    borderBottom: `1px solid ${c.silverGray}`,
    letterSpacing: 0,
  },
  tableBodyCell: {
    py: '14px',
    px: '24px',
    height: 56,
    fontSize: 14,
    lineHeight: '18px',
    letterSpacing: '-0.14px',
    color: c.ashGray,
    borderBottom: `1px solid ${c.silverGray}`,
    bgcolor: c.pureWhite,
  },
  tableNameText: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '18px',
    letterSpacing: '-0.14px',
    color: c.pureBlack,
  },
  footerRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    px: 3,
    py: 2,
    minHeight: 64,
  },
  footerText: {
    fontSize: 14,
    lineHeight: '18px',
    letterSpacing: '-0.14px',
    color: c.ashGray,
  },
  pageTitle: {
    fontSize: { xs: 22, sm: 24, lg: 26 },
    fontWeight: 700,
    color: c.pureBlack,
    letterSpacing: '-0.02em',
    lineHeight: 1.2,
  },
  pageSubtitle: {
    color: c.ashGray,
    mt: 1,
    fontSize: { xs: 13, sm: 14 },
    lineHeight: '20px',
  },
  sideDrawerPaper: {
    width: { xs: '100%', sm: 420, md: 480 },
    maxWidth: '100vw',
    height: '100%',
    borderLeft: `1px solid ${c.silverGray}`,
    borderRadius: 0,
    bgcolor: c.pureWhite,
    boxShadow: '-8px 0 32px rgba(0, 0, 0, 0.1)',
  },
  sideDrawerRoot: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
  },
  sideDrawerBody: {
    flex: 1,
    overflowY: 'auto',
    px: 3,
    py: 2.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  sideDrawerActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 1.5,
    px: 3,
    py: 2,
    mt: 'auto',
    flexShrink: 0,
    borderTop: `1px solid ${c.silverGray}`,
    bgcolor: c.pureWhite,
  },
  modalPaper: {
    width: '100%',
    maxWidth: 480,
    m: 2,
    borderRadius: '16px',
    border: `1px solid ${c.silverGray}`,
    bgcolor: c.pureWhite,
    boxShadow: '0px 8px 32px rgba(0, 0, 0, 0.12)',
    overflow: 'hidden',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 2,
    px: 3,
    pt: 3,
    pb: 2,
  },
  modalHeaderMain: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 1.5,
    flex: 1,
    minWidth: 0,
  },
  modalIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 999,
    bgcolor: c.chipYellowBackground,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 600,
    lineHeight: '24px',
    color: c.pureBlack,
    letterSpacing: '-0.02em',
  },
  modalSubtitle: {
    fontSize: 13,
    lineHeight: '18px',
    color: c.ashGray,
    mt: 0.25,
  },
  modalDivider: {
    borderBottom: `1px solid ${c.silverGray}`,
  },
  modalBody: {
    px: 3,
    py: 2.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  modalField: {
    '& .MuiInputLabel-root': {
      fontSize: 14,
      color: c.ashGray,
      '&.Mui-focused': { color: c.ashGray },
    },
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
      fontSize: 14,
      letterSpacing: '-0.14px',
      bgcolor: c.pureWhite,
      '& fieldset': { borderColor: c.lightGrayCCC },
      '&:hover fieldset': { borderColor: c.lightGrayCCC },
      '&.Mui-focused fieldset': { borderColor: c.ashGray, borderWidth: 1 },
    },
    '& .MuiOutlinedInput-input': {
      py: '12px',
      color: c.pureBlack,
      '&::placeholder': { color: c.stoneGray, opacity: 1 },
    },
    '& .MuiFormHelperText-root': {
      mx: 0,
      fontSize: 12,
    },
  },
  modalInfoAlert: {
    borderRadius: '8px',
    border: `1px solid ${c.softSkyBlue}`,
    bgcolor: c.hoverBlue,
    color: c.ashGray,
    fontSize: 13,
    lineHeight: '18px',
    '& .MuiAlert-icon': { color: c.brightBlue },
    '& strong': { color: c.pureBlack, fontWeight: 600 },
  },
  modalActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 1.5,
    px: 3,
    py: 2,
    borderTop: `1px solid ${c.silverGray}`,
  },
  modalCancelButton: {
    minWidth: 88,
    height: 40,
    color: c.ashGray,
    fontWeight: 600,
    fontSize: 13,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    borderRadius: '8px',
    '&:hover': { bgcolor: c.whisperGrey },
  },
  modalOutlinedButton: {
    minWidth: 88,
    height: 40,
    color: c.pureBlack,
    fontWeight: 500,
    fontSize: 14,
    textTransform: 'none',
    borderRadius: '8px',
    borderColor: c.lightGrayCCC,
    '&:hover': { borderColor: c.ashGray, bgcolor: c.whisperGrey },
  },
  modalPrimaryButton: {
    minWidth: 120,
    height: 40,
    px: 2.5,
    bgcolor: c.goldenSun,
    color: c.pureBlack,
    fontWeight: 600,
    fontSize: 14,
    textTransform: 'none',
    borderRadius: '8px',
    boxShadow: 'none',
    '&:hover': { bgcolor: c.goldenSunHover, boxShadow: 'none' },
    '&.Mui-disabled': {
      bgcolor: c.disabledGray,
      color: c.ashGray,
    },
  },
  modalDangerButton: {
    minWidth: 120,
    height: 40,
    fontWeight: 600,
    fontSize: 14,
    textTransform: 'none',
    borderRadius: '8px',
    boxShadow: 'none',
  },
  modalCloseButton: {
    color: c.ashGray,
    mt: -0.5,
    mr: -0.5,
    '&:hover': { bgcolor: c.whisperGrey },
  },
  confirmModalPaper: {
    width: '100%',
    maxWidth: 420,
    m: 2,
    borderRadius: '16px',
    border: `1px solid ${c.silverGray}`,
    bgcolor: c.pureWhite,
    boxShadow: '0px 8px 32px rgba(0, 0, 0, 0.12)',
    overflow: 'hidden',
  },
  confirmModalBody: {
    px: 3,
    py: 2,
  },
  confirmModalText: {
    fontSize: 14,
    lineHeight: '20px',
    letterSpacing: '-0.14px',
    color: c.ashGray,
  },
});
