apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-user-frontend-ingress
  namespace: multi-user
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - multi-user.showroom.lumegalabs.com
      secretName: multi-user-frontend-tls
  rules:
    - host: multi-user.showroom.lumegalabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multi-user-frontend
                port:
                  number: 80
