apiVersion: v1
kind: Service
metadata:
  name: multi-user-frontend
  namespace: multi-user
  labels:
    app: multi-user-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: multi-user-frontend
