import { createTheme } from '@mui/material/styles';

const theme = createTheme({
  typography: {
    fontFamily: '"DM Sans", sans-serif',
  },
  breakpoints: {
    values: {
      xs: 0,
      sm: 600,
      md: 900,
      lg: 1200,
      midLg: 1300,
      xl: 1536,
      xxl: 1600,
    },
  },
  palette: {
    custom: {
      warmYellow: '300E3C',
      warmYellowHover: '#E6A800',
      mustardYellow: '#E6A832',
      softGray: '#E5E7EB',
      successGreen: '#4CAF50',
      freshMint: '#E6F4EA',
      secondaryGray: '#6C757D',
      softIndigo: '#8884d8',
      warmCream: '#F5E3C3',
      lightBorderGray: '#DDDDDD',
      stoneGray: '#A0A0A0',
      pureBlack: '#000000',
      ashGray: '#595959',
      charcoalGray: '#616161',
      goldenrodYellow: '#e0a400',
      coolGray: '#BDBDBD',
      gainsboroGray: '#d0d0d0',
      borderGray: '#D1D5DB',
      goldenOrange: '#e89b00',
      goldenRod: '#e6a92d',
      silverGray: '#E0E0E0',
      pureWhite: '#ffffff',
      lightGrayCCC: '#CCCCCC',
      lightSlateGray: '#C4C4C4',
      lightButterCream: '#FEF6D9',
      honeyGold: '#F6C667',
      sunsetGold: '#F6A700',
      whisperGrey: '#F5F5F5',
      activeGreen: '#45A049',
      ultraLightGray: '#F2F2F2',
      emeraldGreen: '#04786B',
      tealGreen: '#059688',
      disabledGray: '#D6D6D6',
      pastelGreen: '#DCEDC8',
      blushPink: '#F4C7C3',
      pastelYellow: '#F8E7A2',
      mintGreen: '#A7D7C5',
      deepCharcoal: '#333333',
      offWhite: '#FAFAFA',
      deepSlate: '#374151',
      pastelBlue: '#DCE7FF',
      softGreen: '#E8F5E9',
      forestGreen: '#429488',
      tealAccent: '#007171',
      chipGreenBackground: '#DCEDE1',
      chipYellowBackground: '#FEF3C7',
      lightBeige: '#f4f2ec',
      lightestGray: '#F9FAFB',
      goldenYellow: '#FBBF24',
      warmGold: '#FFBE3C',
      amberOrange: '#F59E0B',
      sunnyYellow: '#f5c16c',
      goldenAmber: '#F4B740',
      amberYellow: '#F9B000',
      darkOliveBrown: '#5f5234',
      mutedGray: '#9E9E9E',
      vividAmber: '#ffb300',
      brightBlue: '#1976d2',
      sunflowerYellow: '#FFC107',
      softFreshGreen: '#a5d6a7',
      deepRichGreen: '#388e3c',
      hoverBlue: '#e3f2fd',
      lightGray: '#f9f9f9',
      hoverBorderBlue: '#1565c0',
      goldenSun: '#FEC84B',
      goldenSunHover: '#fdbf36',
      softSkyBlue: '#cce4ff',
      lightNeutralGray: '#EEEEEE',
      sofTealGreen: '#63B9A4',
      paleGray: '#f0f0f0',
      lightOrange: '#ffb74d',
      brightOrange: '#ffa726',
      boldScarlet: '#D13D42',
      creamyBeige: '#FCECCB',
      avatarColors: ['#FCECCB', '#DCEDE1', '#FFE8E4', '#DEF2FF'],
      peachPuff: '#FFE8E4',
      lightBlue: '#e0f2fe',
      lightTeal: '#e0f2f1',
      darkTeal: '#005b4f',
      saffron: '#F3AF1E',
      darkGoldenrod: '#e09e1b',
      limeGreen: '#D1D342',
      mediumLightGray: '#999999',
      lightSilverGray: '#AAAAAA',
      softMintGreen: '#A7D5C2',
      firebrick: '#F8F8F8',
      slateMuted: '#94A3B8',
      slateBody: '#64748B',
      slateInk: '#0F172A',
      tableHeaderBg: '#F8FAFC',
      statusActiveBg: '#ECFDF5',
      statusActiveText: '#065F46',
      statusActiveDot: '#10B981',
      statusInvitedBg: '#FFFBEB',
      statusInvitedText: '#92400E',
      statusInvitedDot: '#F59E0B',
      statusInactiveBg: '#F4F4F5',
      statusInactiveText: '#52525B',
      statusInactiveDot: '#A1A1AA',
      statusRevokedBg: '#FEF2F2',
      statusRevokedText: '#991B1B',
      statusRevokedDot: '#EF4444',
      dangerText: '#B91C1C',
      successActionText: '#047857',
      platinum: '#E5E7EA',
    },
  },
});

export default theme;
